import { Metadata } from 'next';
import { Header } from '@/components//Header';
import { Footer } from '@/components//Footer';
import ContextProvider from '@/components/ContextProvider';
import './globals.css';
export const metadata: Metadata = {
  title: 'Contract e-sign',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-gray-100">
          <ContextProvider>
            <Header />
            {children}
            <Footer />
          </ContextProvider>
        </div>
      </body>
    </html>
  );
}
