import type { Metadata } from 'next';
import LayoutWrapper from '@/components/LayoutWrapper';
import './globals.css';
export const metadata: Metadata = {
  title: 'Contract e-sign',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico', 
  },
};
import connectDB from '../utils/db';

await connectDB();
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <main>
          <LayoutWrapper>{children}</LayoutWrapper>
        </main>
      </body>
    </html>
  );
}
